### ISSUE TITLE
Assertion Failed: Unable to find view at path 'map-autocomplete'

### ISSUE THREAD

**Issue by temecom** [ember-admin/ember-cli-map#6]
I followed the (terse) instructions for google maps but I initially got: 

google-map not found. 

I noticed that the js files have .coffee extensions when installed so I downloaded the zip and overlayed the node_modules files. It inits the component but then throws:

Assertion Failed: Unable to find view at path 'map-autocomplete'

I can see the map-autocomplete.js in the node_modules folder but it is not resolved. 

Is there an installation step missing? I did: 

npm install ember-cli-map

Here is my map.hbs

{{header-bar pageTitle="Map"}}
{{google-map model=model}}
{{navigation-bar hasSaveButton=false goBack="goBack" save="save"}}
{{outlet}}

routes/map.js

import Ember from 'ember';

export default Ember.Route.extend({

    model: function() {
        var map = this.store.createRecord('map', {lat:35, long:117, zoom: 10});
        return map;
    },
 actions: {
          goBack: function () {
              this.transitionTo("user",0);
           }
        }
});

models/map.js

/*
* Map model
*/
import DS from 'ember-data';

export default DS.Model.extend({
      lat:       DS.attr('number'),
      long:      DS.attr('number'),
      zoom:      DS.attr('number'),
      asGoogleMap: ['lat', 'long', 'zoom']
});

**Comment by OpakAlex** [comment]
hello!

It's very strange...
did you put 
```
"ember-cli-map": "git://github.com/ember-admin/ember-cli-map.git"
```
in your package.json?

**Comment by temecom** [comment]
Is that at the root level ?

**Comment by OpakAlex** [comment]
yes

**Comment by temecom** [comment]
That did it after a restart. Is this needed in the instructions or did 
something fail on my side?

I will try with a clean project and let you know if it is unique to the 
project.

Thanks

Chris

**Comment by temecom** [comment]
How do I add additional parameters like map type, poly lines etc? Is the 
map API exposed directly or through ember-cli-map?

**Comment by temecom** [comment]
I created a clean app and the same thing happened.

The cloned project works fine when I run 'npm install' and 'bower 
install' so I think that there is an issue in the npm package or missing 
installation instructions.

As a side note: the npm installs coffee-script files. Is it required to 
install coffee-script or is that built into node/ember-cli?

Thanks

Chris
